export const initialDueAmountClients: DueAmountClients = [
  {
    customerId: "123",
    dueAmount: 323,
    dueDays: 2,
    loan: "type",
    name: "yashraj",
    paidAmount: 877,
    phone: "9867899923",
    totalAmount: 677898,
    totalLateCharges: 79888,
    previousPayments: [
      {
        amount: 50000,
        date: "March(1/4)",
        dueDays: 1,
        status: "Paid",
      },
      {
        amount: 50000,
        date: "March(1/4)",
        dueDays: 1,
        status: "Paid",
      },
      {
        amount: 50000,
        date: "March(1/4)",
        dueDays: 1,
        status: "Paid",
      },
      {
        amount: 50000,
        date: "March(1/4)",
        dueDays: 1,
        status: "Unpaid",
      },
      {
        amount: 50000,
        date: "March(1/4)",
        dueDays: 1,
        status: "Paid",
      },
      {
        amount: 50000,
        date: "March(1/4)",
        dueDays: 1,
        status: "Unpaid",
      },
      {
        amount: 50000,
        date: "March(1/4)",
        dueDays: 1,
        status: "Unpaid",
      },
    ],
  },
  {
    customerId: "333",
    dueAmount: 323,
    dueDays: 2,
    loan: "type",
    name: "yashraj",
    paidAmount: 877,
    phone: "9867899923",
    totalAmount: 677898,
    totalLateCharges: 79888,
    previousPayments: [
      {
        amount: 50000,
        date: "March(1/4)",
        dueDays: 1,
        status: "Paid",
      },
      {
        amount: 50000,
        date: "March(1/4)",
        dueDays: 1,
        status: "Paid",
      },
      {
        amount: 50000,
        date: "March(1/4)",
        dueDays: 1,
        status: "Paid",
      },
    ],
  },
  {
    customerId: "34",
    dueAmount: 323,
    dueDays: 2,
    loan: "type",
    name: "yashraj",
    paidAmount: 877,
    phone: "9867899923",
    totalAmount: 677898,
    totalLateCharges: 79888,
    previousPayments: [
      {
        amount: 50000,
        date: "March(1/4)",
        dueDays: 1,
        status: "Paid",
      },
      {
        amount: 50000,
        date: "March(1/4)",
        dueDays: 1,
        status: "Paid",
      },
      {
        amount: 50000,
        date: "March(1/4)",
        dueDays: 1,
        status: "Paid",
      },
    ],
  },
];

export const initialPropertyClients: PropertyClients = [
  {
    customerId: "221",
    name: "yashraj",
    phone: "8768767782",
    propertyAddress: "akjbcasbkcbaskc",
    propertyType: "Villa",
    propertyValue: 87787,
  },
  {
    customerId: "42332",
    name: "yashraj",
    phone: "8768767782",
    propertyAddress: "akjbcasbkcbaskc",
    propertyType: "Villa",
    propertyValue: 87787,
  },
];

export const initialKycClients: KycClients = {
  verifiedClients: [
    {
      name: "yashraj",
      image: 'https://toppng.com/uploads/preview/stock-person-png-stock-photo-man-11563049686zqeb9zmqjd.png',
      age: 20,
      address: "udaipur",
      email: "yeshrajteli12345@gmail.com",
      phone: "8955774776",
      zoomMeetTime: new Date(),
    },
    {
      name: "yashraj",
      image: 'https://toppng.com/uploads/preview/stock-person-png-stock-photo-man-11563049686zqeb9zmqjd.png',
      age: 20,
      address: "udaipur",
      email: "yeshrajteli12345@gmail.com",
      phone: "8955774776",
      zoomMeetTime: new Date(),
    },
    {
      name: "yashraj",
      image: 'https://toppng.com/uploads/preview/stock-person-png-stock-photo-man-11563049686zqeb9zmqjd.png',
      age: 20,
      address: "udaipur",
      email: "yeshrajteli12345@gmail.com",
      phone: "8955774776",
      zoomMeetTime: new Date(),
    },
    {
      name: "yashraj",
      image: 'https://toppng.com/uploads/preview/stock-person-png-stock-photo-man-11563049686zqeb9zmqjd.png',
      age: 20,
      address: "udaipur",
      email: "yeshrajteli12345@gmail.com",
      phone: "8955774776",
      zoomMeetTime: new Date(),
    },
    {
      name: "yashraj",
      image: 'https://toppng.com/uploads/preview/stock-person-png-stock-photo-man-11563049686zqeb9zmqjd.png',
      age: 20,
      address: "udaipur",
      email: "yeshrajteli12345@gmail.com",
      phone: "8955774776",
      zoomMeetTime: new Date(),
    },
    {
      name: "yashraj",
      image: 'https://toppng.com/uploads/preview/stock-person-png-stock-photo-man-11563049686zqeb9zmqjd.png',
      age: 20,
      address: "udaipur",
      email: "yeshrajteli12345@gmail.com",
      phone: "8955774776",
      zoomMeetTime: new Date(),
    },
    {
      name: "yashraj",
      image: 'https://toppng.com/uploads/preview/stock-person-png-stock-photo-man-11563049686zqeb9zmqjd.png',
      age: 20,
      address: "udaipur",
      email: "yeshrajteli12345@gmail.com",
      phone: "8955774776",
      zoomMeetTime: new Date(),
    },
    {
      name: "yashraj",
      image: 'https://toppng.com/uploads/preview/stock-person-png-stock-photo-man-11563049686zqeb9zmqjd.png',
      age: 20,
      address: "udaipur",
      email: "yeshrajteli12345@gmail.com",
      phone: "8955774776",
      zoomMeetTime: new Date(),
    },
    {
      name: "yashraj",
      image: 'https://www.kevinashleyphotography.com/wp-content/uploads/2015/11/person.jpg',
      age: 20,
      address: "udaipur",
      email: "yeshrajteli12345@gmail.com",
      phone: "8955774776",
      zoomMeetTime: new Date(),
    },
    {
      name: "yashraj",
      image: 'https://th.bing.com/th/id/OIP.TMBh7iPSyZ6GOpAysJ2VBgHaJ4?w=750&h=1000&rs=1&pid=ImgDetMain',
      age: 20,
      address: "udaipur",
      email: "yeshrajteli12345@gmail.com",
      phone: "8955774776",
      zoomMeetTime: new Date(),
    },
  ],
  verifyClients: [
    {
      name: "yashraj",
      image: 'https://toppng.com/uploads/preview/stock-person-png-stock-photo-man-11563049686zqeb9zmqjd.png',
      age: 20,
      address: "udaipur",
      email: "yeshrajteli12345@gmail.com",
      phone: "8955774776",
      zoomMeetTime: new Date(),
    },
    {
      name: "yashraj",
      image: 'https://toppng.com/uploads/preview/stock-person-png-stock-photo-man-11563049686zqeb9zmqjd.png',
      age: 20,
      address: "udaipur",
      email: "yeshrajteli12345@gmail.com",
      phone: "8955774776",
      zoomMeetTime: new Date(),
    },
    {
      name: "yashraj",
      image: 'https://toppng.com/uploads/preview/stock-person-png-stock-photo-man-11563049686zqeb9zmqjd.png',
      age: 20,
      address: "udaipur",
      email: "yeshrajteli12345@gmail.com",
      phone: "8955774776",
      zoomMeetTime: new Date(),
    },
    {
      name: "yashraj",
      image: 'https://toppng.com/uploads/preview/stock-person-png-stock-photo-man-11563049686zqeb9zmqjd.png',
      age: 20,
      address: "udaipur",
      email: "yeshrajteli12345@gmail.com",
      phone: "8955774776",
      zoomMeetTime: new Date(),
    },
    {
      name: "yashraj",
      image: 'https://www.kevinashleyphotography.com/wp-content/uploads/2015/11/person.jpg',
      age: 20,
      address: "udaipur",
      email: "yeshrajteli12345@gmail.com",
      phone: "8955774776",
      zoomMeetTime: new Date(),
    }
  ],
};
